---@meta

---@class Astra
---@field version string
Astra = {
    version = "0.23.1", -- (Should be) Generated by Astra
}

---Schema validation function with support for nested tables and arrays of tables
---@param input_table table
---@param schema table
---@return boolean, string | nil
function Astra.validate_table(input_table, schema) end

---Load your own file into env
---@param file_path string
function Astra.dotenv_load(file_path) end
